from __future__ import annotations

from models import (
    Category,
    Difficulty,
    ExpectedRecordOutcome,
    InventoryRecord,
    NormalizationPolicy,
    RecordStatus,
    TaskDefinition,
    TaskPolicy,
    Unit,
)


COMMON_POLICY = TaskPolicy(
    taxonomy_labels=[
        Category.BEVERAGES,
        Category.DAIRY,
        Category.SNACKS,
        Category.PRODUCE,
        Category.STAPLES,
        Category.PERSONAL_CARE,
        Category.HOUSEHOLD,
        Category.FROZEN,
        Category.UNKNOWN,
    ],
    normalization_policy=NormalizationPolicy(
        allowed_units=[Unit.G, Unit.KG, Unit.ML, Unit.L, Unit.PCS],
        title_case_required=True,
        unit_conversion_rules={
            "1000 ml -> 1 l": "Convert beverage volumes from 1000 ml to 1 l",
            "500 ml -> 0.5 l": "Allowed for normalization, but prefer common retail title formatting",
            "1000 g -> 1 kg": "Convert dry goods from 1000 g to 1 kg when appropriate",
            "ltr -> l": "Normalize ltr/litre/Ltr to l",
            "pc -> pcs": "Normalize pc/pcs/piece/pieces to pcs",
        },
        duplicate_match_rule=(
            "Merge only if records belong to the same store and represent the same normalized "
            "product identity: brand + normalized title + normalized size/pack."
        ),
        price_sanity_note=(
            "Correct clearly impossible prices when the intended value is obvious; otherwise flag for review."
        ),
    ),
    policy_snippets=[
        "Normalize titles into clean retail-facing names using title case.",
        "Use approved units only: g, kg, ml, l, pcs.",
        "Do not merge records across stores.",
        "Do not guess when product identity is ambiguous; flag for review.",
        "Packaged produce and loose produce should not be merged unless clearly identical.",
        "If a price looks off by an obvious factor of 10 or decimal issue, correct it. Otherwise escalate.",
    ],
)


TASKS: dict[str, TaskDefinition] = {
    "easy_title_unit_cleanup": TaskDefinition(
        task_id="easy_title_unit_cleanup",
        title="Basic title and unit normalization for a single store batch",
        difficulty=Difficulty.EASY,
        objective=(
            "Clean a small batch of obvious formatting issues so the records are ready for downstream catalog use."
        ),
        records=[
            InventoryRecord(
                record_id="easy_1",
                store_id="blr_store_101",
                raw_title="Coca cola 1000ml",
                brand="Coca Cola",
                quantity_value=1000,
                quantity_unit=Unit.ML,
                price=89.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="easy_2",
                store_id="blr_store_101",
                raw_title="Amul taaza toned milk 500 ML",
                brand="Amul",
                quantity_value=500,
                quantity_unit=Unit.ML,
                price=29.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="easy_3",
                store_id="blr_store_101",
                raw_title="Banana 6 pc",
                quantity_value=6,
                quantity_unit=Unit.PCS,
                price=42.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="easy_4",
                store_id="blr_store_101",
                raw_title="Aashirvaad atta 5kg",
                brand="Aashirvaad",
                quantity_value=5,
                quantity_unit=Unit.KG,
                price=289.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="easy_5",
                store_id="blr_store_101",
                raw_title="Lays magic masala 52 g",
                brand="Lays",
                quantity_value=52,
                quantity_unit=Unit.G,
                price=20.0,
                source="merchant_csv",
            ),
        ],
        policy=COMMON_POLICY,
        expected_outcomes=[
            ExpectedRecordOutcome(
                record_id="easy_1",
                normalized_title="Coca Cola 1 L",
                category=Category.BEVERAGES,
                quantity_value=1,
                quantity_unit=Unit.L,
                price=89.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="easy_2",
                normalized_title="Amul Taaza Toned Milk 500 Ml",
                category=Category.DAIRY,
                quantity_value=500,
                quantity_unit=Unit.ML,
                price=29.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="easy_3",
                normalized_title="Banana 6 Pcs",
                category=Category.PRODUCE,
                quantity_value=6,
                quantity_unit=Unit.PCS,
                price=42.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="easy_4",
                normalized_title="Aashirvaad Atta 5 Kg",
                category=Category.STAPLES,
                quantity_value=5,
                quantity_unit=Unit.KG,
                price=289.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="easy_5",
                normalized_title="Lays Magic Masala 52 G",
                category=Category.SNACKS,
                quantity_value=52,
                quantity_unit=Unit.G,
                price=20.0,
                status=RecordStatus.CLEANED,
            ),
        ],
        max_steps=10,
    ),
    "medium_duplicate_price_fix": TaskDefinition(
        task_id="medium_duplicate_price_fix",
        title="Resolve duplicates and fix one obvious pricing issue",
        difficulty=Difficulty.MEDIUM,
        objective=(
            "Clean a medium-size batch by merging true duplicates, correcting an obvious price error, "
            "and filling missing category information."
        ),
        records=[
            InventoryRecord(
                record_id="med_1",
                store_id="hyd_store_22",
                raw_title="Coke 1 ltr",
                brand="Coca Cola",
                quantity_value=1,
                quantity_unit=Unit.L,
                price=90.0,
                source="pos_sync",
            ),
            InventoryRecord(
                record_id="med_2",
                store_id="hyd_store_22",
                raw_title="Coca Cola 1000 ml",
                brand="Coca Cola",
                quantity_value=1000,
                quantity_unit=Unit.ML,
                price=90.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_3",
                store_id="hyd_store_22",
                raw_title="Surf exel easy wash 1kg",
                brand="Surf Excel",
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=32.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_4",
                store_id="hyd_store_22",
                raw_title="Amul taza milk 500ml pack",
                brand="Amul",
                quantity_value=500,
                quantity_unit=Unit.ML,
                price=28.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_5",
                store_id="hyd_store_22",
                raw_title="Bananas pack of six",
                quantity_value=6,
                quantity_unit=Unit.PCS,
                price=40.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_6",
                store_id="hyd_store_22",
                raw_title="Tata salt 1kg",
                brand="Tata",
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=28.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_7",
                store_id="hyd_store_22",
                raw_title="Colgate strong teeth 200g",
                brand="Colgate",
                quantity_value=200,
                quantity_unit=Unit.G,
                price=118.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="med_8",
                store_id="hyd_store_22",
                raw_title="Tomato 1 kg",
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=34.0,
                source="merchant_csv",
            ),
        ],
        policy=COMMON_POLICY,
        expected_outcomes=[
            ExpectedRecordOutcome(
                record_id="med_1",
                normalized_title="Coca Cola 1 L",
                category=Category.BEVERAGES,
                quantity_value=1,
                quantity_unit=Unit.L,
                price=90.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_2",
                normalized_title="Coca Cola 1 L",
                category=Category.BEVERAGES,
                quantity_value=1,
                quantity_unit=Unit.L,
                price=90.0,
                status=RecordStatus.MERGED,
                merged_into="med_1",
            ),
            ExpectedRecordOutcome(
                record_id="med_3",
                normalized_title="Surf Excel Easy Wash 1 Kg",
                category=Category.HOUSEHOLD,
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=320.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_4",
                normalized_title="Amul Taaza Milk 500 Ml Pack",
                category=Category.DAIRY,
                quantity_value=500,
                quantity_unit=Unit.ML,
                price=28.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_5",
                normalized_title="Bananas Pack Of 6",
                category=Category.PRODUCE,
                quantity_value=6,
                quantity_unit=Unit.PCS,
                price=40.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_6",
                normalized_title="Tata Salt 1 Kg",
                category=Category.STAPLES,
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=28.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_7",
                normalized_title="Colgate Strong Teeth 200 G",
                category=Category.PERSONAL_CARE,
                quantity_value=200,
                quantity_unit=Unit.G,
                price=118.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="med_8",
                normalized_title="Tomato 1 Kg",
                category=Category.PRODUCE,
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=34.0,
                status=RecordStatus.CLEANED,
            ),
        ],
        max_steps=12,
    ),
    "hard_ambiguous_multisource_batch": TaskDefinition(
        task_id="hard_ambiguous_multisource_batch",
        title="Safety-aware curation of an ambiguous multi-source inventory batch",
        difficulty=Difficulty.HARD,
        objective=(
            "Curate a difficult batch with duplicate-like records, pricing anomalies, missing attributes, "
            "and true ambiguity. Clean what is safe, and flag what should not be guessed."
        ),
        records=[
            InventoryRecord(
                record_id="hard_1",
                store_id="mum_store_7",
                raw_title="Coke Zero can 300ml",
                brand="Coca Cola",
                quantity_value=300,
                quantity_unit=Unit.ML,
                price=40.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_2",
                store_id="mum_store_7",
                raw_title="Coca Cola Zero 330 ml can",
                brand="Coca Cola",
                quantity_value=330,
                quantity_unit=Unit.ML,
                price=42.0,
                source="pos_sync",
            ),
            InventoryRecord(
                record_id="hard_3",
                store_id="mum_store_7",
                raw_title="Tomato loose 1kg",
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=28.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_4",
                store_id="mum_store_7",
                raw_title="Tomatoes 1 kg pack",
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=32.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_5",
                store_id="mum_store_7",
                raw_title="Amul Gold 6x1L",
                brand="Amul",
                quantity_value=6,
                quantity_unit=Unit.PCS,
                pack_count=6,
                price=450.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_6",
                store_id="mum_store_7",
                raw_title="Amul gold milk 1 litre",
                brand="Amul",
                quantity_value=1,
                quantity_unit=Unit.L,
                price=78.0,
                source="pos_sync",
            ),
            InventoryRecord(
                record_id="hard_7",
                store_id="mum_store_7",
                raw_title="Ariel matic front load 2 kg",
                brand="Ariel",
                quantity_value=2,
                quantity_unit=Unit.KG,
                price=18.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_8",
                store_id="mum_store_7",
                raw_title="Frozen green peas 500 gm",
                brand="Safal",
                quantity_value=500,
                quantity_unit=Unit.G,
                price=110.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_9",
                store_id="mum_store_7",
                raw_title="Green peas 500g",
                quantity_value=500,
                quantity_unit=Unit.G,
                price=36.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_10",
                store_id="mum_store_7",
                raw_title="Good knight liquid refill 45ml",
                brand="Good Knight",
                quantity_value=45,
                quantity_unit=Unit.ML,
                price=780.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_11",
                store_id="mum_store_7",
                raw_title="Britania bread 400g",
                brand="Britannia",
                quantity_value=400,
                quantity_unit=Unit.G,
                price=45.0,
                source="merchant_csv",
            ),
            InventoryRecord(
                record_id="hard_12",
                store_id="mum_store_7",
                raw_title="Eggs 12",
                quantity_value=12,
                quantity_unit=Unit.PCS,
                price=84.0,
                source="merchant_csv",
            ),
        ],
        policy=COMMON_POLICY,
        expected_outcomes=[
            ExpectedRecordOutcome(
                record_id="hard_1",
                normalized_title="Coke Zero Can 300 Ml",
                category=Category.BEVERAGES,
                quantity_value=300,
                quantity_unit=Unit.ML,
                price=40.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_2",
                normalized_title="Coca Cola Zero 330 Ml Can",
                category=Category.BEVERAGES,
                quantity_value=330,
                quantity_unit=Unit.ML,
                price=42.0,
                status=RecordStatus.FLAGGED,
                should_flag=True,
            ),
            ExpectedRecordOutcome(
                record_id="hard_3",
                normalized_title="Tomato Loose 1 Kg",
                category=Category.PRODUCE,
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=28.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_4",
                normalized_title="Tomatoes 1 Kg Pack",
                category=Category.PRODUCE,
                quantity_value=1,
                quantity_unit=Unit.KG,
                price=32.0,
                status=RecordStatus.FLAGGED,
                should_flag=True,
            ),
            ExpectedRecordOutcome(
                record_id="hard_5",
                normalized_title="Amul Gold Milk 6 X 1 L",
                category=Category.DAIRY,
                quantity_value=6,
                quantity_unit=Unit.PCS,
                pack_count=6,
                price=450.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_6",
                normalized_title="Amul Gold Milk 1 L",
                category=Category.DAIRY,
                quantity_value=1,
                quantity_unit=Unit.L,
                price=78.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_7",
                normalized_title="Ariel Matic Front Load 2 Kg",
                category=Category.HOUSEHOLD,
                quantity_value=2,
                quantity_unit=Unit.KG,
                price=180.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_8",
                normalized_title="Safal Frozen Green Peas 500 G",
                category=Category.FROZEN,
                quantity_value=500,
                quantity_unit=Unit.G,
                price=110.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_9",
                normalized_title="Green Peas 500 G",
                category=Category.PRODUCE,
                quantity_value=500,
                quantity_unit=Unit.G,
                price=36.0,
                status=RecordStatus.FLAGGED,
                should_flag=True,
            ),
            ExpectedRecordOutcome(
                record_id="hard_10",
                normalized_title="Good Knight Liquid Refill 45 Ml",
                category=Category.HOUSEHOLD,
                quantity_value=45,
                quantity_unit=Unit.ML,
                price=78.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_11",
                normalized_title="Britannia Bread 400 G",
                category=Category.STAPLES,
                quantity_value=400,
                quantity_unit=Unit.G,
                price=45.0,
                status=RecordStatus.CLEANED,
            ),
            ExpectedRecordOutcome(
                record_id="hard_12",
                normalized_title="Eggs 12 Pcs",
                category=Category.DAIRY,
                quantity_value=12,
                quantity_unit=Unit.PCS,
                price=84.0,
                status=RecordStatus.CLEANED,
            ),
        ],
        max_steps=14,
    ),
}


DEFAULT_TASK_ID = "easy_title_unit_cleanup"
TASK_ORDER = [
    "easy_title_unit_cleanup",
    "medium_duplicate_price_fix",
    "hard_ambiguous_multisource_batch",
]
